# Generated by Django 5.2.4 on 2025-08-03 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_call_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('character_type', models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Sister', 'Sister'), ('Brother', 'Brother'), ('Partner', 'Partner'), ('Friend', 'Friend'), ('Grandmother', 'Grandmother'), ('Grandfather', 'Grandfather'), ('Mentor', 'Mentor'), ('Child', 'Child')], max_length=50)),
                ('emotion_model', models.CharField(max_length=100)),
                ('voice_model', models.CharField(max_length=100)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('unlock_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['unlock_order', 'created_at'],
                'unique_together': {('user', 'character_type')},
            },
        ),
    ]
