# Generated by Django 5.2.4 on 2025-08-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_character"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="credits",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Credits used to unlock characters. Each character costs 5 credits.",
            ),
        ),
    ]
