# Generated by Django 5.2.4 on 2025-08-15 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_membership_credits"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="nickname",
            field=models.CharField(
                blank=True,
                help_text="What the character usually calls the user.",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Summary of the chat between user and relation."
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.relation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
