# Generated by Django 5.2.4 on 2025-08-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_character_nickname_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='emocoins',
            field=models.PositiveIntegerField(default=0, help_text='Emocoins earned through activities.'),
        ),
    ]
