# Generated by Django 5.2.4 on 2025-08-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_customuser_emocoins'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='character',
            name='is_unlocked',
        ),
        migrations.RemoveField(
            model_name='character',
            name='unlock_order',
        ),
    ]
