# Generated by Django 5.2.4 on 2025-08-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_character_options_remove_character_is_unlocked_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='character',
            unique_together=set(),
        ),
    ]
