# Generated by Django 5.2.4 on 2025-08-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0008_alter_character_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "credits",
                    models.PositiveIntegerField(
                        default=0, help_text="Credits granted by this code."
                    ),
                ),
                (
                    "max_redemptions",
                    models.PositiveIntegerField(
                        default=1, help_text="Maximum times this code can be redeemed."
                    ),
                ),
                (
                    "redeemed_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this code has been redeemed.",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, help_text="Is this code active?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
