# Generated by Django 5.2.4 on 2025-08-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0010_customuser_date_of_birth_customuser_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="credits",
            field=models.PositiveIntegerField(
                default=15,
                help_text="Credits used to unlock characters. Each character costs 5 credits.",
            ),
        ),
    ]
