# Generated by Django 5.2.4 on 2025-08-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0011_alter_membership_credits"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="streak",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Time spent communicating with this character (in minutes)",
            ),
        ),
    ]
