# Generated by Django 5.2.4 on 2025-08-17 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_character_streak'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('task_type', models.CharField(choices=[('REVIEW', 'App Review'), ('REFERRAL', 'Referral'), ('DAILY_LOGIN', 'Daily Login'), ('FIRST_CALL', 'First Call'), ('COMPLETE_PROFILE', 'Complete Profile'), ('SOCIAL_SHARE', 'Social Share')], max_length=20)),
                ('reward_emocoins', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('max_completions_per_user', models.PositiveIntegerField(default=1, help_text='How many times a user can complete this task')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('what_you_like', models.TextField(help_text='What do you like most about the app?')),
                ('what_to_improve', models.TextField(blank=True, help_text='What could be improved?')),
                ('recommend_to_others', models.BooleanField(help_text='Would you recommend this app to others?')),
                ('favorite_feature', models.CharField(blank=True, help_text="What's your favorite feature?", max_length=200)),
                ('additional_feedback', models.TextField(blank=True, help_text='Any additional feedback?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reward_given', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(help_text='Unique referral code generated for sharing', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral_used_at', models.DateTimeField(auto_now_add=True)),
                ('referrer_reward_given', models.BooleanField(default=False)),
                ('referred_reward_given', models.BooleanField(default=False)),
                ('referrer_reward_emocoins', models.PositiveIntegerField(default=10)),
                ('referred_reward_emocoins', models.PositiveIntegerField(default=5)),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='received_referral', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_referrals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralCodeRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('credits_received', models.PositiveIntegerField()),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.referralcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'referral_code')},
            },
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('reward_claimed', models.BooleanField(default=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'task')},
            },
        ),
    ]
