# Generated by Django 5.2.4 on 2025-08-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_task_appreview_userreferral_referralcoderedemption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreview',
            name='what_you_like',
            field=models.TextField(blank=True, help_text='What do you like most about the app?'),
        ),
    ]
