# Generated by Django 5.2.4 on 2025-08-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_appreview_what_you_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='User has accepted the Terms and Conditions'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When user accepted the Terms and Conditions', null=True),
        ),
    ]
